---
downloads: ~/.ansible-downloads/

configure_sudoers: yes

dotfiles_repo: https://github.com/NickBlomberg/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .macos
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  - cookiecutter
  - doxygen
  - git
  - go
  - gpg
  - hugo
  - python
  - python3
  - node
  - rsync
  - ssh-copy-id
  - tmux
  - tree
  - wget
  - youtube-dl

homebrew_taps:
  - homebrew/core
  - homebrew/dupes
  - homebrew/versions
  - caskroom/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - android-studio
  - appcleaner
  - atom
  - coconutbattery
  - dropbox
  - firefox
  - flux
  - google-chrome
  - handbrake
  - iterm2
  - java
  - macvim
  - onyx
  - pycharm
  - skype
  - spectacle
  - torbrowser
  - vagrant
  - virtualbox
  - viscosity
  - vlc
  - ynab

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids: []
mas_email: ""
mas_password: ""
