---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/preferences.yml

    # TODO: Use sudo once .macos can be run via root with no user interaction.
    - name: Run .macos dotfile
      shell: ~/.macos --no-restart
      changed_when: false
