---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  roles:
    - geerlingguy.homebrew
    - geerlingguy.dotfiles

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/preferences.yml

    - name: Run .macos dotfile
      shell: bash /Users/vagrant/.macos --no-restart
      changed_when: false
      become: yes
